# Generated by Django 2.2.14 on 2022-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Horror'), ('R', 'Romance'), ('P', 'Politics')], max_length=2),
        ),
    ]
